/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc721RoyalitySol from "./erc721Royality.sol";
export type { erc721RoyalitySol };
export type { BridgeNFT } from "./BridgeNFT";
