/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc721RoyalitySol from "./erc721Royality.sol";
export { BridgeNFT__factory } from "./BridgeNFT__factory";
